// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5XaU9i_gUeLxMfgmyoQ03HV823UhsAI',
    appId: '1:876842317392:android:3ebc9f6384e84e4d308355',
    messagingSenderId: '876842317392',
    projectId: 'smartstay-3c784',
    storageBucket: 'smartstay-3c784.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaM6vzftHaPkQd5SWMnkPVbeKhSq4E4N4',
    appId: '1:876842317392:web:97ae01e6580fd52e308355',
    messagingSenderId: '876842317392',
    projectId: 'smartstay-3c784',
    authDomain: 'smartstay-3c784.firebaseapp.com',
    storageBucket: 'smartstay-3c784.firebasestorage.app',
    measurementId: 'G-W8EWPZ53J4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr1lHjkxmowXHvlLXxXq_Zk5Js6Vo6jLA',
    appId: '1:876842317392:ios:d588682eb6b2eb77308355',
    messagingSenderId: '876842317392',
    projectId: 'smartstay-3c784',
    storageBucket: 'smartstay-3c784.firebasestorage.app',
    iosBundleId: 'com.example.smartstay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaM6vzftHaPkQd5SWMnkPVbeKhSq4E4N4',
    appId: '1:876842317392:web:11ffcc946888bd9f308355',
    messagingSenderId: '876842317392',
    projectId: 'smartstay-3c784',
    authDomain: 'smartstay-3c784.firebaseapp.com',
    storageBucket: 'smartstay-3c784.firebasestorage.app',
    measurementId: 'G-03J8ZT2XKF',
  );

}